name: single-cell-reproduction
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # Core Python
  - python=3.9
  - pip
  
  # Data Science & Visualization
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn

  # Single-Cell Analysis
  - scanpy>=1.9
  - anndata
  - h5py
  - statsmodels
  - tqdm

  # Notebook & Reproducibility
  - jupyterlab
  - ipykernel
  - nbconvert

  # Biological Databases / Enrichment
  - pip:
      - gprofiler-official>=1.0.0
